# This is a basic workflow to help you get started with boman.ai

name: Bomanai Scanner
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Boman-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs Boman Package and runs scan on code repository
      - name: Installing Boman
        run: sudo pip install boman-cli
      - name: Run scan
        env:
          APP: ${{ secrets.APP_TOKEN }}
          USER: ${{ secrets.CUSTOMER_TOKEN }}
        run: sudo boman-cli -a run -at "$APP" -ct "$USER"